###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Pinduca",
    "senha": "123",
    "email": "Pinduca@gmail.com",
    "telefone": "(48) 9 9999-9999"
}

###

DELETE http://localhost:3000/usuarios/10

###

PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome": "Pindas",
    "senha": "12345",
    "email": "Pinduca@gmail.com",
    "telefone": "(48) 9 9999-9999"
}

###

GET http://localhost:3000/categorias

###

POST http://localhost:3000/categorias
Content-Type: application/json

{
    "nome": "Emagracimento"
}

###

DELETE http://localhost:3000/categorias/2

###

PUT http://localhost:3000/categorias/3
Content-Type: application/json

{
    "nome": "Deixar de ser obeso"
}